// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package processqueue.actions;

import processqueue.queuehandler.QueueHandler;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Returns the information about each Queue. It shows for each Queue, its name, possible queue size and the currently running/waiting actions
 */
public class QueueMonitorInfo extends CustomJavaAction<java.lang.String>
{
	private java.lang.Boolean ShowDebug;

	public QueueMonitorInfo(IContext context, java.lang.Boolean ShowDebug)
	{
		super(context);
		this.ShowDebug = ShowDebug;
	}

	@Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return QueueHandler.getQueueHandler().monitor( this.ShowDebug );
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "QueueMonitorInfo";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
